name = input("What is your name? ")
print(f"Hello, {name.upper()}!")
print(f"Hello, {name.lower()}!")
print(f"Hello, {name.title()}!")
takım = input("What is your favorite football team? ")
print(f"Your favorite football team is {takım}!")
print(f"Your favorite football team is {len(takım)} characters long!")
cümle = input("Please enter a sentence: ")
print(f"Your sentence with spaces replaced by underscores: {cümle.replace(' ', '_')}")

cümle2 = input("Please enter another sentence: ")
print(f"Your sentence length: {len(cümle2)}")
print(f"Your sentence has {cümle2.count(' ')} spaces.")
print(f"Your sentence has {cümle2.count('a')} 'a' characters.")
print(f"Your sentence in uppercase: {cümle2.upper()}")
print(f"Your sentence in lowercase: {cümle2.lower()}")
